### ISSUE TITLE
exitcode is always 1?

### ISSUE THREAD

**Issue by zheli** [cuttlesoft/ecs-deploy.py#11]
It seems the exitcode is always 1? In that case it would hard to tell when the command succeeds/fails..

**Comment by zheli** [comment]
` >> ecs-deploy-py -c staging-20161214 -n hyperdrive-endpoint -i 064841643618.dkr.ecr.eu-west-1.amazonaws.com/hyperdrive/backend:master
SUCCES
>> echo $?
1`

**Comment by zheli** [comment]
I got the exitcode by type in "echo $?" after a successful deploy.

**Comment by frankV** [comment]
we'll look into it

**Comment by jtrotsky** [comment]
This also messes up CI pipeline, as it throws error even when it is SUCCESS.
<img width="1084" alt="screenshot 2017-02-26 12 44 50" src="https://cloud.githubusercontent.com/assets/5625795/23335774/66c26eda-fc21-11e6-89d9-0c1b7740e330.png">

**Comment by frankV** [comment]
Alright, we're gonna triage this later in the week. Sorry guys - should be an easy fix. If anyone want's to issue a PR it might speed things up.
